apiVersion: v1
kind: Service
metadata:
  name: chatfold-backend
  namespace: chatfold
  labels:
    app: chatfold-backend
    component: backend
    environment: test
spec:
  type: ClusterIP
  selector:
    app: chatfold-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
