fullnameOverride: chatfold-ingress-nginx
controller:
  # Use VKE mirror registry (registry.k8s.io is not accessible in China)
  image:
    registry: vke-cn-shanghai.cr.volces.com
    image: vke/ingress-nginx-controller
    tag: "v1.11.5"
    digest: ""
  ingressClassName: chatfold-nginx
  ingressClassResource:
    name: chatfold-nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/chatfold-ingress-nginx"
  scope:
    enabled: true
    namespace: chatfold
  electionID: chatfold-ingress-leader
  replicaCount: 1
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  config:
    proxy-read-timeout: "600"
    proxy-send-timeout: "600"
    proxy-buffering: "off"
  admissionWebhooks:
    patch:
      image:
        registry: vke-cn-shanghai.cr.volces.com
        image: vke/kube-webhook-certgen
        tag: "v1.5.2"
        digest: ""
defaultBackend:
  enabled: false
